[platformio]
default_envs = crazy-eyes

extra_configs =
  config/platformio-m5stack.ini

[env]
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
upload_speed = 1500000

build_flags = 
lib_deps =

lib_ldf_mode = deep

[build-target]
extends = release

[esp-now]
build_flags =
    -DESP_NOW_CHANNEL=0
lib_deps =
    https://github.com/3110/m5stack-esp-now.git#v0.0.3

[env:crazy-eyes]
extends = m5unified, m5stack-stop-watch, esp-now, build-target
build_src_filter = +<crazy-eyes/>
board_build.embed_files = 
    data/crazy_eyes_open.jpg
    data/crazy_eyes_close.jpg
build_flags = 
    ${m5unified.build_flags}
    ${m5stack-stop-watch.build_flags}
    ${esp-now.build_flags}
    ${build-target.build_flags}
lib_deps = 
    ${m5unified.lib_deps}
    ${m5stack-stop-watch.lib_deps}
    ${esp-now.lib_deps}

[env:crazy-eyes-controller]
extends = m5unified, m5stack-chain-dualkey, esp-now, build-target
build_src_filter = +<crazy-eyes-controller/>
build_flags =
    ${m5unified.build_flags}
    ${m5stack-chain-dualkey.build_flags}
    ${esp-now.build_flags}
    ${build-target.build_flags}
lib_deps =
    ${m5unified.lib_deps}
    ${m5stack-chain-dualkey.lib_deps}
    ${esp-now.lib_deps}
